### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by Triangulum9r** [ccbrown/teslacam-recovery#2]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/14811322/89136584-49de5f00-d4e9-11ea-8913-1a97565e6644.png">

USB 3.0 FD:

  Product ID:	0xfa05
  Vendor ID:	0x154b  (PNY Technologies Inc.)
  Version:	10.75
  Serial Number:	2818487484
  Speed:	Up to 5 Gb/s
  Manufacturer:	PNY Technologies
  Location ID:	0x00100000 / 3
  Current Available (mA):	900
  Current Required (mA):	600
  Extra Operating Current (mA):	0
  Media:
USB 3.0 FD:
  Capacity:	32 GB (31,999,393,792 bytes)
  Removable Media:	Yes
  BSD Name:	disk2
  Logical Unit:	0
  Partition Map Type:	MBR (Master Boot Record)
  S.M.A.R.T. status:	Verified
  USB Interface:	0
  Volumes:
TESLADRIVE:
  Capacity:	32 GB (31,998,345,216 bytes)
  File System:	ExFAT
  BSD Name:	disk2s1
  Content:	Windows_NTFS
  Volume UUID:	2AEA4959-5B43-3C10-826A-FC7CFE9ABF01

```
Traceback (most recent call last):
  File "./run.py", line 42, in <module>
    totalClusters = totalSectors/sectorsPerCluster
ZeroDivisionError: integer division or modulo by zero
```

**Comment by scor** [comment]
seeing the same error here, this worked before, I wonder if this has to do with the way the vehicle formats the USB drive, that's the only difference I can think of from before. Seeing your volume named "TESLADRIVE" is just like mine and that's how it's named when you format inside the car.

where is this output from? I don't see Vendor ID and Serial Number in my Disk Util.

**Comment by scor** [comment]
Both totalSectors and sectorsPerCluster are null. The script can no longer understand the boot sector. Here is what it looks like for me when running dumpBinary(bootSector)
```
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    3B  B4  BA  5E  00  00  00  20 
21  00  07  2E  83  6B  00  08    00  00  00  F8  51  0E  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  00  00 
00  00  00  00  00  00  00  00    00  00  00  00  00  00  55  AA 
```

**Comment by janelletam** [comment]
is there a solution?

**Comment by TheLinuxGuy** [comment]
facing this same issue... any workarounds?

**Comment by adamurban** [comment]
The issue here is that the script was written for FAT32 drives and tesla now formats drives using exFAT. I've spent a few minutes on a horrible hack to support exFAT; will open a PR (and hopefully someone with some time can clean this up...)

**Comment by scor** [comment]
Thanks so much @adamurban ! I tried your PR on two different USB keys I had and they both worked! I think if anything the exFAT should be the default format since that's how Tesla vehicles will format keys now, and move the FAT32 as an option (if someone can build an autodetect feature then it will be even better!)

**Comment by dhogborg** [comment]
PR #3 resolved this for me

**Comment by ccbrown** [comment]
This should be resolved now.
