### ISSUE TITLE
TypeError: byte vs int

### ISSUE THREAD

**Issue by gabrielswank** [ccbrown/teslacam-recovery#4]
When running script, receive the error: 

line 30, in <module>
`    bytesPerSectorShift,       = struct.unpack("<B", bootSector[0x6C]) `
TypeError: a bytes-like object is required, not 'int'

**Comment by Piste** [comment]
I have the same issue, even after adding all the parentheses to bring this script up to Python3's expectations. I'm not sure how to fix this. Did you find a solution @gabrielswank ?

**Comment by ccbrown** [comment]
This should be fixed now. Python 3 is happy now.
